# Generated by Django 4.2.3 on 2023-08-01 19:55

import apps.destinos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_1', models.ImageField(blank=True, null=True, upload_to=apps.destinos.models.Destino.upload_path_1, verbose_name='Foto 1')),
                ('foto_2', models.ImageField(blank=True, null=True, upload_to=apps.destinos.models.Destino.upload_path_2, verbose_name='Foto 2')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('meta', models.CharField(default=None, max_length=160)),
                ('texto_descritivo', models.TextField(blank=True, default=None, null=True, verbose_name='Texto Descritivo')),
                ('preco', models.IntegerField(verbose_name='Preço')),
            ],
        ),
    ]
