# Generated by Django 4.2.3 on 2023-07-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='preco',
            field=models.CharField(max_length=10, verbose_name='Preço'),
        ),
    ]
