# Generated by Django 4.2.3 on 2023-08-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='texto_descritivo',
            field=models.TextField(blank=True, default=None, max_length=160, null=True, verbose_name='Texto Descritivo'),
        ),
    ]
