# Generated by Django 4.2.3 on 2023-07-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0002_alter_destino_foto_alter_destino_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media_root/destinos/<django.db.models.fields.CharField>', verbose_name='Imagem'),
        ),
    ]
