# Generated by Django 4.2.3 on 2023-08-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0002_alter_destino_texto_descritivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='texto_descritivo',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Texto Descritivo'),
        ),
    ]
