# Generated by Django 4.2.3 on 2023-07-24 20:47

import apps.destinos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0004_alter_destino_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.destinos.models.Destino.upload_path, verbose_name='Imagem'),
        ),
    ]
