# Generated by Django 4.2.3 on 2023-07-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0005_alter_destino_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='preco',
            field=models.FloatField(max_length=10, verbose_name='Preço'),
        ),
    ]
