# Generated by Django 4.2.3 on 2023-07-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
