# Generated by Django 4.2.3 on 2023-07-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0002_alter_depoimento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
