# Generated by Django 4.2.3 on 2023-07-24 21:01

import apps.viagens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0005_alter_depoimento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.viagens.models.Depoimento.upload_path),
        ),
    ]
